# -*- coding: utf-8 -*-
"""ADA-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsXHGYIZscIzOUI2HbC4zVcLV8QeRhG7
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
from google.colab import files

# Step 1: Upload datasets
uploaded = files.upload()  # Upload files
print("\nUploaded files:", uploaded)

# Load the uploaded text data
text_file = list(uploaded.keys())[0]  # First uploaded file is assumed to be text data
text_data = pd.read_csv(text_file)
print("\nFirst few rows of the text data:")
print(text_data.head())

# Print the column names to check for any discrepancies
print("\nColumns in the uploaded text dataset:")
print(text_data.columns)

# Step 2: Identify and process text data (Independent of image data)
# Check if the specified columns exist in the dataset
text_columns = ['Symptoms', 'Chronic Conditions', 'Lifestyle Factors']  # Modify based on your needs

# Print the actual column names from the dataset to identify discrepancies
print("\nColumns available in the dataset:")
print(text_data.columns)

# Find columns that exist in both `text_columns` and the dataset
available_columns = [col for col in text_columns if col in text_data.columns]

# Print the available columns to verify what's found
print("\nAvailable text columns in dataset:")
print(available_columns)

# Step 2a: Convert text columns using TF-IDF (only if columns are available)
if available_columns:
    # If text columns are available, process them
    X_text = text_data[available_columns].fillna('')  # Fill missing values with empty strings
    vectorizer = TfidfVectorizer(max_features=100)  # Adjust the feature limit as needed
    text_features = vectorizer.fit_transform(X_text.astype(str)).toarray()

    # Convert the processed text into a DataFrame
    text_feature_names = vectorizer.get_feature_names_out()  # Get feature names directly from the vectorizer
    text_features_df = pd.DataFrame(text_features, columns=text_feature_names)

    print("\nProcessed text features:")
    print(text_features_df.head())
else:
    print("\nNo text columns found in the dataset. Skipping text data processing.")

# Step 3: Handle image data independently
# Load the uploaded image data (assuming second uploaded file is image data)
image_file = list(uploaded.keys())[1]  # Second uploaded file is assumed to be image data
image_data = pd.read_csv(image_file)
print("\nFirst few rows of the image data:")
print(image_data.head())

# Image data includes columns such as 'Sex', 'AgeBaseline', 'HistoryDiabetes', etc.
image_features = image_data.drop(columns=['Patient ID', 'TimeToEventMonths', 'EventCKD35', 'TIME_YEAR'], axis=1, errors='ignore')
image_features = image_features.fillna(0)

# Convert categorical variables in image data to numeric if necessary
for column in image_features.columns:
    if image_features[column].dtype == 'object':
        label_encoder = LabelEncoder()
        image_features[column] = label_encoder.fit_transform(image_features[column].astype(str))

# Step 4: Combine text and image features for model training (if desired)
# If no text data, use only the image data
if available_columns:
    X_combined = pd.concat([text_features_df, image_features], axis=1)
else:
    X_combined = image_features

# Step 5: Define the target column (you can adjust this based on your dataset)
# Check if the target column exists
target_column = 'Chronic Conditions'  # Modify if necessary
if target_column not in text_data.columns:
    print(f"Target column '{target_column}' not found in the dataset. Please check the column names.")
    # If the target column doesn't exist, you may want to choose another one, like 'Symptoms' or 'Lifestyle Factors'
else:
    # Ensure target variable is numeric (you can adjust this based on your column)
    y = text_data[target_column].fillna('Unknown')  # Adjust as per your target column
    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y)

    # Step 6: Ensure alignment of feature set (X_combined) and target (y)
    # Convert y to a pandas Series to ensure alignment
    y = pd.Series(y)

    # Drop rows where either X_combined or y have missing values (if any)
    # Ensure that both X_combined and y have the same index and length
    combined_data = X_combined.copy()
    combined_data['target'] = y

    # Remove rows with missing values in any column
    combined_data = combined_data.dropna()

    # Now, split the combined_data back into X_combined and y
    X_combined = combined_data.drop(columns=['target'])
    y = combined_data['target']

    # Step 7: Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.3, random_state=42)

    # Step 8: Logistic Regression
    log_reg_model = LogisticRegression(max_iter=1000)
    log_reg_model.fit(X_train, y_train)

    # Step 9: Predictions and evaluation
    y_pred = log_reg_model.predict(X_test)

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    # Step 10: Dimensionality reduction with PCA
    pca = PCA(n_components=2)
    X_pca = pca.fit_transform(X_combined)

    # Ensure X_pca and y have matching lengths
    print("Shape of X_pca:", X_pca.shape)
    print("Length of y:", len(y))

    # Step 10: Plotting the PCA results
    plt.figure(figsize=(8, 6))
    plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='coolwarm', alpha=0.7)
    plt.xlabel('Principal Component 1')
    plt.ylabel('Principal Component 2')
    plt.title('PCA Visualization of Combined Dataset')
    plt.colorbar(label='Target')
    plt.show()

!pip install scikit-learn opencv-python numpy pandas

import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Step 1: Upload text data CSV using Google Colab's file upload feature
uploaded_text_file = files.upload()  # This opens the file upload dialog
text_df = pd.read_csv(next(iter(uploaded_text_file)))  # Read the uploaded CSV file

# Step 2: Clean up column names to remove spaces and make them lowercase
text_df.columns = text_df.columns.str.strip().str.lower()

# Step 3: Check the column names to verify what columns are available
print("Cleaned Text Data Columns:", text_df.columns)

# Inspect the first few rows of the text data to confirm the structure
print(text_df.head())

# Step 4: Assigning features and labels
# Features - selecting columns that contain clinical information
features = text_df[['historydiabetes', 'historychd', 'historyvascular', 'historysmoking',
                    'historyhtn', 'historydld', 'historyobesity', 'dldmeds', 'dmmeds',
                    'htnmeds', 'aceiarb', 'cholesterolbaseline', 'creatininebaseline',
                    'egfrbaseline', 'sbpbaseline', 'dbpbaseline', 'bmibaseline', 'timetoeventmonths']]

# Labels - 'eventckd35' is the column indicating CKD event occurrence
labels = text_df['eventckd35']

# Step 5: Preprocessing the features (standardization)
scaler = StandardScaler()
X = scaler.fit_transform(features)

y = labels

# Step 6: Split the dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Models to be trained
models = {
    "SVM": SVC(),
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier()
}

# Step 7: Training and evaluating the models for classification
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"{model_name} Accuracy: {model.score(X_test, y_test):.3f}")
    print(f"Classification Report for {model_name}:\n{classification_report(y_test, y_pred)}")
    print(f"Confusion Matrix for {model_name}:\n{confusion_matrix(y_test, y_pred)}\n")

import pandas as pd
from google.colab import files
from transformers import AutoTokenizer, AutoModelForCausalLM
import time
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Step 1: Upload CSV File
uploaded = files.upload()

# Step 2: Load the dataset after file upload
text_data = pd.read_csv(next(iter(uploaded)))  # Load the first uploaded file automatically

# Normalize column names (strip spaces, lowercase)
text_data.columns = text_data.columns.str.strip().str.lower()

# Verify the columns to check if normalization was successful
print("Columns in the dataset:", text_data.columns)

# Step 3: Ensure 'ckd stage' column exists and handle it appropriately
if 'ckd stage' not in text_data.columns:
    raise ValueError("The column 'ckd stage' does not exist in the data.")

# Ensure 'ckd stage' is numeric (coerce non-numeric values to NaN)
text_data['ckd stage'] = pd.to_numeric(text_data['ckd stage'], errors='coerce')

# Step 4: Check for missing columns before proceeding
required_columns = ['patient id', 'age', 'symptoms', 'blood pressure', 'glucose levels',
                    'serum creatinine', 'egfr', 'chronic conditions', 'lifestyle factors']

missing_columns = [col for col in required_columns if col not in text_data.columns]
if missing_columns:
    raise ValueError(f"Missing columns in the dataset: {', '.join(missing_columns)}")

# Step 5: Create the prompt for the LLM
def create_prompt(row):
    try:
        prompt = (f"Patient ID: {row['patient id']}, Age: {row['age']}, Symptoms: {row['symptoms']}, "
                  f"Blood Pressure: {row['blood pressure']}, Glucose Levels: {row['glucose levels']}, "
                  f"Serum Creatinine: {row['serum creatinine']}, eGFR: {row['egfr']}, "
                  f"Chronic Conditions: {row['chronic conditions']}, Lifestyle Factors: {row['lifestyle factors']}. "
                  f"Does this patient have CKD?")
        return prompt
    except KeyError as e:
        raise ValueError(f"Missing column in the data for prompt creation: {e}")

# Step 6: Apply prompt creation
text_data['prompt'] = text_data.apply(create_prompt, axis=1)

# Step 7: Load Auto tokenizer and model for DistilGPT-2
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

# Add padding token for tokenizer
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

# Step 8: Generate responses using the tokenizer and model
def generate_response(prompt):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, padding=True, max_length=128)
    attention_mask = inputs["attention_mask"]

    outputs = model.generate(
        inputs["input_ids"],
        attention_mask=attention_mask,
        max_length=200,
        num_return_sequences=1,
        no_repeat_ngram_size=2
    )
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    if "CKD" in response or "chronic kidney disease" in response.lower():
        return "This patient is suffering from CKD."
    else:
        return "This patient is not suffering from CKD."

# Step 9: Apply text generation on the dataset with timing
start_time = time.time()
text_data['generated_response'] = text_data['prompt'].apply(generate_response)
end_time = time.time()

# Performance calculations
num_prompts = len(text_data)
total_time = end_time - start_time
avg_time_per_prompt = total_time / num_prompts

# Step 10: Create a final dataframe with only the required columns
final_output = text_data[['patient id', 'age', 'generated_response']]

# Save the output to an Excel file
output_file = "CKD_predictions_with_performance.xlsx"
final_output.to_excel(output_file, index=False)

# Provide a download link for the file
files.download(output_file)

# Step 11: Print performance metrics
print("Performance Metrics:")
print(f"Total time for {num_prompts} predictions: {total_time:.2f} seconds")
print(f"Average time per prediction: {avg_time_per_prompt:.2f} seconds")

# Step 12: Map generated responses to "CKD" vs. "Not CKD"
# This assumes the 'ckd stage' column contains numeric values like 0 or 1 where 1 means CKD
# Convert the actual 'ckd stage' into "CKD" (if stage > 0) vs "Not CKD"
text_data['actual_ckd'] = text_data['ckd stage'].apply(lambda x: "CKD" if x > 0 else "Not CKD")

# Step 13: Map the generated responses to "CKD" vs "Not CKD"
text_data['predicted_ckd'] = text_data['generated_response'].apply(
    lambda x: "CKD" if "suffering from CKD" in x else "Not CKD"
)

# Step 14: Calculate metrics
accuracy = accuracy_score(text_data['actual_ckd'], text_data['predicted_ckd'])
precision = precision_score(text_data['actual_ckd'], text_data['predicted_ckd'], pos_label='CKD')
recall = recall_score(text_data['actual_ckd'], text_data['predicted_ckd'], pos_label='CKD')
f1 = f1_score(text_data['actual_ckd'], text_data['predicted_ckd'], pos_label='CKD')

# Step 15: Print the metrics
print("Performance Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Show the first few responses to verify
print(final_output.head())

import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Step 1: Upload text data CSV using Google Colab's file upload feature
uploaded_text_file = files.upload()  # This opens the file upload dialog
text_df = pd.read_csv(next(iter(uploaded_text_file)))  # Read the uploaded CSV file

# Step 2: Clean up column names to remove spaces and make them lowercase
text_df.columns = text_df.columns.str.strip().str.lower()

# Step 3: Check the column names to verify what columns are available
print("Cleaned Text Data Columns:", text_df.columns)

# Inspect the first few rows of the text data to confirm the structure
print(text_df.head())

# Step 4: Assigning features and labels
# Features - selecting columns that contain clinical information
features = text_df[['historydiabetes', 'historychd', 'historyvascular', 'historysmoking',
                    'historyhtn', 'historydld', 'historyobesity', 'dldmeds', 'dmmeds',
                    'htnmeds', 'aceiarb', 'cholesterolbaseline', 'creatininebaseline',
                    'egfrbaseline', 'sbpbaseline', 'dbpbaseline', 'bmibaseline', 'timetoeventmonths']]

# Labels - 'eventckd35' is the column indicating CKD event occurrence
labels = text_df['eventckd35']

# Step 5: Preprocessing the features (standardization)
scaler = StandardScaler()
X = scaler.fit_transform(features)

y = labels

# Step 6: Split the dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Models to be trained (add more traditional models here)
models = {
    "SVM": SVC(),
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Linear Discriminant Analysis": LinearDiscriminantAnalysis(),
    "XGBoost": XGBClassifier(eval_metric='mlogloss')  # XGBoost requires eval_metric for multiclass problems
}

# Step 7: Training and evaluating the models for classification
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"{model_name} Accuracy: {model.score(X_test, y_test):.3f}")
    print(f"Classification Report for {model_name}:\n{classification_report(y_test, y_pred)}")
    print(f"Confusion Matrix for {model_name}:\n{confusion_matrix(y_test, y_pred)}\n")

import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Step 1: Upload text data CSV using Google Colab's file upload feature
uploaded_text_file = files.upload()  # This opens the file upload dialog
text_df = pd.read_csv(next(iter(uploaded_text_file)))  # Read the uploaded CSV file

# Step 2: Clean up column names to remove spaces and make them lowercase
text_df.columns = text_df.columns.str.strip().str.lower()

# Step 3: Check the column names to verify what columns are available
print("Cleaned Text Data Columns:", text_df.columns)

# Inspect the first few rows of the text data to confirm the structure
print(text_df.head())

# Step 4: Assigning features and labels
# Features - selecting columns that contain clinical information
features = text_df[['historydiabetes', 'historychd', 'historyvascular', 'historysmoking',
                    'historyhtn', 'historydld', 'historyobesity', 'dldmeds', 'dmmeds',
                    'htnmeds', 'aceiarb', 'cholesterolbaseline', 'creatininebaseline',
                    'egfrbaseline', 'sbpbaseline', 'dbpbaseline', 'bmibaseline', 'timetoeventmonths']]

# Labels - 'eventckd35' is the column indicating CKD event occurrence
labels = text_df['eventckd35']

# Step 5: Preprocessing the features (standardization)
scaler = StandardScaler()
X = scaler.fit_transform(features)

y = labels

# Step 6: Split the dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Models to be trained (including traditional and advanced models)
models = {
    "SVM": SVC(),
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Linear Discriminant Analysis": LinearDiscriminantAnalysis(),
    "XGBoost": XGBClassifier(eval_metric='mlogloss')  # XGBoost requires eval_metric for multiclass problems
}

# Step 7: Training and evaluating the models for classification
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"{model_name} Accuracy: {model.score(X_test, y_test):.3f}")
    print(f"Classification Report for {model_name}:\n{classification_report(y_test, y_pred)}")
    print(f"Confusion Matrix for {model_name}:\n{confusion_matrix(y_test, y_pred)}\n")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Accuracy values for each model
models = ['SVM', 'Logistic Regression', 'Random Forest', 'K-Nearest Neighbors',
          'Decision Tree', 'Naive Bayes', 'Linear Discriminant Analysis', 'XGBoost']
accuracies = [0.513, 0.524, 0.487, 0.490, 0.511, 0.522, 0.524, 0.516]

# Confusion matrices for each model
conf_matrices = {
    'SVM': [[275, 207], [280, 238]],
    'Logistic Regression': [[286, 196], [280, 238]],
    'Random Forest': [[276, 206], [307, 211]],
    'K-Nearest Neighbors': [[241, 241], [269, 249]],
    'Decision Tree': [[242, 240], [249, 269]],
    'Naive Bayes': [[286, 196], [282, 236]],
    'Linear Discriminant Analysis': [[286, 196], [280, 238]],
    'XGBoost': [[261, 221], [263, 255]]
}

# Plotting Accuracy bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x=models, y=accuracies, palette='Blues_d')
plt.title('Model Accuracy Comparison', fontsize=16)
plt.ylabel('Accuracy', fontsize=12)
plt.xlabel('Models', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Plotting Confusion Matrices
fig, axes = plt.subplots(2, 4, figsize=(20, 10))
axes = axes.flatten()

for i, (model, cm) in enumerate(conf_matrices.items()):
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                xticklabels=['Predicted No CKD', 'Predicted CKD'],
                yticklabels=['Actual No CKD', 'Actual CKD'],
                ax=axes[i], square=True, annot_kws={'size': 16})
    axes[i].set_title(model, fontsize=14)
    axes[i].set_xlabel('Predicted Labels', fontsize=12)
    axes[i].set_ylabel('True Labels', fontsize=12)

plt.tight_layout()
plt.show()