# -*- coding: utf-8 -*-
"""Hybrid approach.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmVJP13TDzdcMH3cqIg7YNMEVMbTZvki
"""

from google.colab import files
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

# Step 1: Upload files from Google Colab
print("Please upload your datasets:")

# Upload the files
uploaded = files.upload()

# Load the uploaded files into pandas DataFrames
trad_data = pd.read_csv('5000textdata-Updated ones.csv')  # Traditional dataset (5000 samples)
llm_data = pd.read_csv('297countofdatasets-LLM.csv')  # LLM dataset (594 samples)

# Step 2: Preprocessing the traditional dataset
# Assuming 'CKD Stage' is the target column in the dataset
# Remove 'Patient ID' and 'Diagnosis Date' columns and handle categorical data for model training
X_trad = trad_data.drop(columns=['Patient ID', 'Diagnosis Date', 'CKD Stage'])  # Features for traditional dataset
y_trad = trad_data['CKD Stage']  # Labels for traditional dataset

# Step 3: Encode categorical features for both datasets
# Handle categorical variables in both datasets using LabelEncoder
label_encoder = LabelEncoder()

# Apply LabelEncoder to all columns in both datasets
for col in X_trad.select_dtypes(include=['object']).columns:
    X_trad[col] = label_encoder.fit_transform(X_trad[col])

# Encode the target variable for traditional dataset (y_trad)
y_trad_encoded = label_encoder.fit_transform(y_trad)

# Similarly for LLM dataset, assuming it also has categorical features
X_llm = llm_data.drop(columns=['Patient ID', 'Diagnosis Date', 'CKD Stage'])  # Features for LLM dataset
y_llm = llm_data['CKD Stage']  # Labels for LLM dataset

# Apply LabelEncoder to all columns in the LLM dataset
for col in X_llm.select_dtypes(include=['object']).columns:
    X_llm[col] = label_encoder.fit_transform(X_llm[col])

# Encode the target variable for LLM dataset (y_llm)
y_llm_encoded = label_encoder.fit_transform(y_llm)

# Step 4: Train traditional and LLM models
# Train the RandomForest model on traditional data
trad_model = RandomForestClassifier()
trad_model.fit(X_trad, y_trad_encoded)

# Train the Logistic Regression model on LLM data
llm_model = LogisticRegression(max_iter=10000)
llm_model.fit(X_trad, y_trad_encoded)  # Ensure both models are trained on the same dataset for hybrid prediction

# Step 5: Evaluate Traditional Model
traditional_predictions = trad_model.predict(X_trad)  # Predictions from RandomForest model
traditional_accuracy = accuracy_score(y_trad_encoded, traditional_predictions)
print(f"Traditional Model Accuracy: {traditional_accuracy}")
print("Classification Report for Traditional Model:")
print(classification_report(y_trad_encoded, traditional_predictions))
print("Confusion Matrix for Traditional Model:")
print(confusion_matrix(y_trad_encoded, traditional_predictions))

# ROC Curve and AUC for Traditional Model
fpr_trad, tpr_trad, thresholds_trad = roc_curve(y_trad_encoded, trad_model.predict_proba(X_trad)[:, 1], pos_label=label_encoder.transform(['Stage 5: Kidney Failure'])[0])
auc_trad = roc_auc_score(y_trad_encoded, trad_model.predict_proba(X_trad), multi_class='ovr')
print(f"AUC for Traditional Model: {auc_trad}")
plt.figure()
plt.plot(fpr_trad, tpr_trad, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % auc_trad)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Traditional Model')
plt.legend(loc="lower right")
plt.show()

# Step 6: Evaluate LLM Model
llm_predictions = llm_model.predict(X_trad)  # Predictions from LLM model (using X_trad to match traditional model)
llm_accuracy = accuracy_score(y_trad_encoded, llm_predictions)
print(f"LLM Model Accuracy: {llm_accuracy}")
print("Classification Report for LLM Model:")
print(classification_report(y_trad_encoded, llm_predictions))
print("Confusion Matrix for LLM Model:")
print(confusion_matrix(y_trad_encoded, llm_predictions))

# ROC Curve and AUC for LLM Model
fpr_llm, tpr_llm, thresholds_llm = roc_curve(y_trad_encoded, llm_model.predict_proba(X_trad)[:, 1], pos_label=label_encoder.transform(['Stage 5: Kidney Failure'])[0])
auc_llm = roc_auc_score(y_trad_encoded, llm_model.predict_proba(X_trad), multi_class='ovr')
print(f"AUC for LLM Model: {auc_llm}")
plt.figure()
plt.plot(fpr_llm, tpr_llm, color='blue', lw=2, label='ROC curve (area = %0.2f)' % auc_llm)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for LLM Model')
plt.legend(loc="lower right")
plt.show()

# Step 7: Combine both models' predictions (Hybrid Approach)
# Now both models are evaluated on the same dataset (X_trad)
# Get the predicted probabilities for each class
hybrid_predictions_prob = (trad_model.predict_proba(X_trad) + llm_model.predict_proba(X_trad)) / 2

# Step 8: Evaluate Combined Hybrid Model
# For multi-class, the hybrid model will return probabilities for all classes
# Calculate ROC and AUC for the combined model using probabilities
auc_hybrid = roc_auc_score(y_trad_encoded, hybrid_predictions_prob, multi_class='ovr')
print(f"AUC for Combined Hybrid Model: {auc_hybrid}")
fpr_hybrid, tpr_hybrid, thresholds_hybrid = roc_curve(y_trad_encoded, hybrid_predictions_prob[:, 1], pos_label=label_encoder.transform(['Stage 5: Kidney Failure'])[0])

# Plot ROC Curve for Hybrid Model
plt.figure()
plt.plot(fpr_hybrid, tpr_hybrid, color='green', lw=2, label='ROC curve (area = %0.2f)' % auc_hybrid)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Combined Hybrid Model')
plt.legend(loc="lower right")
plt.show()

from google.colab import files
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import BertTokenizer, BertModel
import torch

# Step 1: Upload files from Google Colab
print("Please upload your datasets:")

# Upload the files
uploaded = files.upload()

# Load the uploaded files into pandas DataFrames
trad_data = pd.read_csv('5000textdata-Updated ones.csv')  # Traditional dataset (5000 samples)
llm_data = pd.read_csv('297countofdatasets-LLM.csv')  # LLM dataset (594 samples)

# Step 2: Preprocessing the traditional dataset
X_trad = trad_data.drop(columns=['Patient ID', 'Diagnosis Date', 'CKD Stage'])  # Features for traditional dataset
y_trad = trad_data['CKD Stage']  # Labels for traditional dataset

# Step 3: Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained('bert-base-uncased')

# Function to generate BERT embeddings
def get_bert_embeddings(text_data):
    inputs = tokenizer(list(text_data), return_tensors='pt', padding=True, truncation=True, max_length=512)
    with torch.no_grad():
        outputs = bert_model(**inputs)
        embeddings = outputs.last_hidden_state[:, 0, :]  # CLS token embedding
    return embeddings.numpy()

# Apply BERT embeddings to text-based columns in the traditional dataset
for col in X_trad.select_dtypes(include=['object']).columns:
    X_trad[col] = get_bert_embeddings(X_trad[col])

# Encode the target variable for traditional dataset
label_encoder = LabelEncoder()
y_trad_encoded = label_encoder.fit_transform(y_trad)

# Similarly for LLM dataset
X_llm = llm_data.drop(columns=['Patient ID', 'Diagnosis Date', 'CKD Stage'])  # Features for LLM dataset
y_llm = llm_data['CKD Stage']  # Labels for LLM dataset

# Apply BERT embeddings to text-based columns in the LLM dataset
for col in X_llm.select_dtypes(include=['object']).columns:
    X_llm[col] = get_bert_embeddings(X_llm[col])

# Encode the target variable for LLM dataset
y_llm_encoded = label_encoder.fit_transform(y_llm)

# Step 4: Train traditional and LLM models
trad_model = RandomForestClassifier()
trad_model.fit(X_trad, y_trad_encoded)

llm_model = LogisticRegression(max_iter=10000)
llm_model.fit(X_trad, y_trad_encoded)  # Training both on X_trad for comparison

# Step 5: Evaluate Traditional Model
traditional_predictions = trad_model.predict(X_trad)
traditional_accuracy = accuracy_score(y_trad_encoded, traditional_predictions)
print(f"Traditional Model Accuracy: {traditional_accuracy}")
print("Classification Report for Traditional Model:")
print(classification_report(y_trad_encoded, traditional_predictions))
print("Confusion Matrix for Traditional Model:")
print(confusion_matrix(y_trad_encoded, traditional_predictions))

# ROC Curve and AUC for Traditional Model
fpr_trad, tpr_trad, thresholds_trad = roc_curve(y_trad_encoded, trad_model.predict_proba(X_trad)[:, 1])
auc_trad = roc_auc_score(y_trad_encoded, trad_model.predict_proba(X_trad), multi_class='ovr')
print(f"AUC for Traditional Model: {auc_trad}")
plt.figure()
plt.plot(fpr_trad, tpr_trad, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % auc_trad)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Traditional Model')
plt.legend(loc="lower right")
plt.show()

# Step 6: Evaluate LLM Model
llm_predictions = llm_model.predict(X_trad)  # Predictions from LLM model
llm_accuracy = accuracy_score(y_trad_encoded, llm_predictions)
print(f"LLM Model Accuracy: {llm_accuracy}")
print("Classification Report for LLM Model:")
print(classification_report(y_trad_encoded, llm_predictions))
print("Confusion Matrix for LLM Model:")
print(confusion_matrix(y_trad_encoded, llm_predictions))

# ROC Curve and AUC for LLM Model
fpr_llm, tpr_llm, thresholds_llm = roc_curve(y_trad_encoded, llm_model.predict_proba(X_trad)[:, 1])
auc_llm = roc_auc_score(y_trad_encoded, llm_model.predict_proba(X_trad), multi_class='ovr')
print(f"AUC for LLM Model: {auc_llm}")
plt.figure()
plt.plot(fpr_llm, tpr_llm, color='blue', lw=2, label='ROC curve (area = %0.2f)' % auc_llm)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for LLM Model')
plt.legend(loc="lower right")
plt.show()

# Step 7: Combine both models' predictions (Hybrid Approach)
hybrid_predictions_prob = (trad_model.predict_proba(X_trad) + llm_model.predict_proba(X_trad)) / 2

# Step 8: Evaluate Combined Hybrid Model
auc_hybrid = roc_auc_score(y_trad_encoded, hybrid_predictions_prob, multi_class='ovr')
print(f"AUC for Combined Hybrid Model: {auc_hybrid}")
fpr_hybrid, tpr_hybrid, thresholds_hybrid = roc_curve(y_trad_encoded, hybrid_predictions_prob[:, 1])

plt.figure()
plt.plot(fpr_hybrid, tpr_hybrid, color='green', lw=2, label='ROC curve (area = %0.2f)' % auc_hybrid)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Combined Hybrid Model')
plt.legend(loc="lower right")
plt.show()

import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.datasets import make_classification

# Example: Generate a synthetic classification dataset for demonstration purposes
# Replace this with your actual data loading code
X_trad, y_trad_encoded = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Step 1: Hyperparameter tuning for Random Forest
rf_params = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

rf_grid_search = GridSearchCV(estimator=RandomForestClassifier(), param_grid=rf_params, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')
rf_grid_search.fit(X_trad, y_trad_encoded)

print("Best parameters for Random Forest: ", rf_grid_search.best_params_)

# Step 2: Hyperparameter tuning for Logistic Regression
log_reg_params = {
    'C': [0.1, 1, 10],
    'penalty': ['l2', 'elasticnet'],
    'solver': ['lbfgs', 'saga']
}

log_reg_grid_search = GridSearchCV(estimator=LogisticRegression(max_iter=10000), param_grid=log_reg_params, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')
log_reg_grid_search.fit(X_trad, y_trad_encoded)

print("Best parameters for Logistic Regression: ", log_reg_grid_search.best_params_)

# Step 3: Cross-validation for more reliable performance estimates

# Cross-validation for Random Forest model
rf_cross_val_score = cross_val_score(rf_grid_search.best_estimator_, X_trad, y_trad_encoded, cv=5, scoring='accuracy')
print(f"Cross-validation scores for Random Forest: {rf_cross_val_score}")
print(f"Mean cross-validation score for Random Forest: {rf_cross_val_score.mean()}")

# Cross-validation for Logistic Regression model
log_reg_cross_val_score = cross_val_score(log_reg_grid_search.best_estimator_, X_trad, y_trad_encoded, cv=5, scoring='accuracy')
print(f"Cross-validation scores for Logistic Regression: {log_reg_cross_val_score}")
print(f"Mean cross-validation score for Logistic Regression: {log_reg_cross_val_score.mean()}")

# Step 4: Ensemble Methods (Stacking)

# Create base models
base_learners = [
    ('rf', rf_grid_search.best_estimator_),
    ('lr', log_reg_grid_search.best_estimator_)
]

# Meta-model (Logistic Regression)
meta_model = LogisticRegression(max_iter=10000)

# Stacked model
stacked_model = StackingClassifier(estimators=base_learners, final_estimator=meta_model)

# Train stacked model
stacked_model.fit(X_trad, y_trad_encoded)

# Evaluate Stacked Model
stacked_predictions = stacked_model.predict(X_trad)
stacked_accuracy = accuracy_score(y_trad_encoded, stacked_predictions)
print(f"Stacked Model Accuracy: {stacked_accuracy}")

# Step 5: Handling Class Imbalance

# Apply SMOTE to balance the class distribution
smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X_trad, y_trad_encoded)

# Train models on the resampled data (SMOTE)
rf_model_smote = RandomForestClassifier(n_estimators=100, max_depth=10)
rf_model_smote.fit(X_smote, y_smote)

log_reg_model_smote = LogisticRegression(max_iter=10000)
log_reg_model_smote.fit(X_smote, y_smote)

# Evaluate models after applying SMOTE
rf_smote_predictions = rf_model_smote.predict(X_smote)
log_reg_smote_predictions = log_reg_model_smote.predict(X_smote)

print("Random Forest model (after SMOTE) Accuracy:", accuracy_score(y_smote, rf_smote_predictions))
print("Logistic Regression model (after SMOTE) Accuracy:", accuracy_score(y_smote, log_reg_smote_predictions))

# Optional: Adjusting class weights instead of using SMOTE
rf_model_weighted = RandomForestClassifier(n_estimators=100, max_depth=10, class_weight='balanced')
rf_model_weighted.fit(X_trad, y_trad_encoded)

log_reg_model_weighted = LogisticRegression(max_iter=10000, class_weight='balanced')
log_reg_model_weighted.fit(X_trad, y_trad_encoded)

# Evaluate models after adjusting class weights
rf_weighted_predictions = rf_model_weighted.predict(X_trad)
log_reg_weighted_predictions = log_reg_model_weighted.predict(X_trad)

print("Random Forest model (class weights) Accuracy:", accuracy_score(y_trad_encoded, rf_weighted_predictions))
print("Logistic Regression model (class weights) Accuracy:", accuracy_score(y_trad_encoded, log_reg_weighted_predictions))

# Check the column names and first few rows of the data
print(trad_data.columns)  # List of column names in the traditional dataset
print(trad_data.head())   # Display first few rows of the dataset