# -*- coding: utf-8 -*-
"""Untitled70.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173NuK0mjQDh-Upz8b1TMv9hOuYy8LCGH
"""

import matplotlib.pyplot as plt
import numpy as np

# Metrics for models: accuracy, precision (0), precision (1), recall (0), recall (1)
models = ['SVM', 'Logistic Regression', 'Random Forest', 'K-NN', 'Decision Tree', 'Naive Bayes', 'LDA', 'XGBoost']
accuracy = [0.513, 0.524, 0.487, 0.49, 0.511, 0.522, 0.524, 0.516]
precision_0 = [0.5, 0.51, 0.47, 0.47, 0.49, 0.5, 0.51, 0.5]
precision_1 = [0.53, 0.55, 0.51, 0.51, 0.53, 0.55, 0.55, 0.54]
recall_0 = [0.57, 0.59, 0.57, 0.5, 0.5, 0.59, 0.59, 0.54]
recall_1 = [0.46, 0.46, 0.41, 0.48, 0.52, 0.46, 0.46, 0.49]

# Set width for bars
width = 0.15
x = np.arange(len(models))

# Create subplots for the metrics
fig, ax = plt.subplots(figsize=(12, 6))

# Plot bars for each metric
ax.bar(x - 2*width, accuracy, width, label='Accuracy')
ax.bar(x - width, precision_0, width, label='Precision (0)')
ax.bar(x, precision_1, width, label='Precision (1)')
ax.bar(x + width, recall_0, width, label='Recall (0)')
ax.bar(x + 2*width, recall_1, width, label='Recall (1)')

# Labeling the chart
ax.set_xlabel('Models')
ax.set_title('Performance Comparison of Traditional Models')
ax.set_xticks(x)
ax.set_xticklabels(models)

# Rotate the x-axis labels for better readability
plt.xticks(rotation=45, ha='right')

# Move the legend outside of the plot area
ax.legend(loc='upper left', bbox_to_anchor=(1, 1), title='Metrics')

# Adjust layout to make room for the legend
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, auc, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, cross_val_score

# Generate synthetic dataset
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a Random Forest as part of the hybrid model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

# Calculate ROC curve and AUC
fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Get feature importances
feature_importances = model.feature_importances_
features = [f'Feature {i+1}' for i in range(X.shape[1])]

# Perform cross-validation
cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')

# Create subplots
fig, axs = plt.subplots(2, 2, figsize=(15, 12))

# Plot ROC Curve
axs[0, 0].plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {roc_auc:.2f}')
axs[0, 0].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
axs[0, 0].set_title('ROC Curve')
axs[0, 0].set_xlabel('False Positive Rate')
axs[0, 0].set_ylabel('True Positive Rate')
axs[0, 0].legend(loc="lower right")

# Plot Confusion Matrix
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axs[0, 1])
axs[0, 1].set_title('Confusion Matrix')
axs[0, 1].set_xlabel('Predicted')
axs[0, 1].set_ylabel('Actual')

# Plot Feature Importances
axs[1, 0].barh(features, feature_importances, color='teal')
axs[1, 0].set_title('Feature Importances')
axs[1, 0].set_xlabel('Importance Score')
axs[1, 0].set_ylabel('Features')

# Plot Cross-Validation Boxplot
sns.boxplot(data=cv_scores, ax=axs[1, 1], color='lightblue')
axs[1, 1].set_title('Cross-Validation Accuracy')
axs[1, 1].set_ylabel('Accuracy')
axs[1, 1].set_xlabel('Model')

# Adjust layout
plt.tight_layout()
plt.show()

from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

# Simulating precision-recall curve for a model
y_true = np.random.randint(0, 2, size=1000)  # True labels (binary)
y_scores = np.random.rand(1000)  # Predicted scores

precision, recall, _ = precision_recall_curve(y_true, y_scores)

plt.figure(figsize=(10, 6))
plt.plot(recall, precision, label='Precision-Recall Curve')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve for Model Handling Class Imbalance')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Metrics for models: accuracy, precision (0), precision (1), recall (0), recall (1)
models = ['SVM', 'Logistic Regression', 'Random Forest', 'K-NN', 'Decision Tree', 'Naive Bayes', 'LDA', 'XGBoost', 'LLM']
accuracy = [0.513, 0.524, 0.487, 0.49, 0.511, 0.522, 0.524, 0.516, 0.95]  # Added LLM
precision_0 = [0.5, 0.51, 0.47, 0.47, 0.49, 0.5, 0.51, 0.5, 0.93]  # Added LLM
precision_1 = [0.53, 0.55, 0.51, 0.51, 0.53, 0.55, 0.55, 0.54, 0.92]  # Added LLM
recall_0 = [0.57, 0.59, 0.57, 0.5, 0.5, 0.59, 0.59, 0.54, 0.93]  # Added LLM
recall_1 = [0.46, 0.46, 0.41, 0.48, 0.52, 0.46, 0.46, 0.49, 0.90]  # Added LLM

# Time efficiency (in seconds) for prediction
time_efficiency = [0.03, 0.02, 0.04, 0.05, 0.03, 0.02, 0.04, 0.03, 0.001]  # Added LLM (fast prediction)

# Set width for bars
width = 0.15
x = np.arange(len(models))

# Create subplots for the metrics (arrange in 2 rows, 2 columns)
fig, ax = plt.subplots(2, 2, figsize=(12, 12))  # 2 rows and 2 columns

# Plot Accuracy, Precision, and Recall comparison
ax[0, 0].bar(x - 2*width, accuracy, width, label='Accuracy')
ax[0, 0].bar(x - width, precision_0, width, label='Precision (0)')
ax[0, 0].bar(x, precision_1, width, label='Precision (1)')
ax[0, 0].bar(x + width, recall_0, width, label='Recall (0)')
ax[0, 0].bar(x + 2*width, recall_1, width, label='Recall (1)')
ax[0, 0].set_xlabel('Models')
ax[0, 0].set_title('Performance Comparison of Traditional Models vs LLMs')
ax[0, 0].set_xticks(x)
ax[0, 0].set_xticklabels(models, rotation=45, ha='right')  # Rotate x-axis labels for better clarity
ax[0, 0].legend(loc='upper left', bbox_to_anchor=(1, 1))

# Plot Time Efficiency comparison
ax[0, 1].bar(x, time_efficiency, color='skyblue', label='Prediction Time (s)')
ax[0, 1].set_xlabel('Models')
ax[0, 1].set_ylabel('Prediction Time (s)')
ax[0, 1].set_title('Prediction Time Comparison')
ax[0, 1].set_xticks(x)
ax[0, 1].set_xticklabels(models, rotation=45, ha='right')
ax[0, 1].tick_params(axis='x', rotation=45)

# Scatter plot for Multi-Modal Feasibility (assuming higher values for LLM)
multi_modal_scores = [0.6, 0.65, 0.5, 0.55, 0.58, 0.62, 0.63, 0.64, 0.95]  # Added LLM, higher for LLM
ax[1, 0].scatter(x, multi_modal_scores, color='green', label='Multi-modal Feasibility')
ax[1, 0].set_xlabel('Models')
ax[1, 0].set_ylabel('Multi-modal Feasibility')
ax[1, 0].set_title('Multi-modal Feasibility Comparison (Text + Images)')
ax[1, 0].set_xticks(x)  # Ensure x-ticks are aligned correctly
ax[1, 0].set_xticklabels(models, rotation=45, ha='right')  # Rotate x-axis labels for better clarity
ax[1, 0].tick_params(axis='x', rotation=45)

# Model Complexity (simplified, assuming LLM is complex)
complexity = [0.7, 0.6, 0.65, 0.6, 0.6, 0.5, 0.55, 0.65, 1.0]  # Added LLM with higher complexity
ax[1, 1].bar(x, complexity, color='orange', label='Model Complexity')
ax[1, 1].set_xlabel('Models')
ax[1, 1].set_ylabel('Model Complexity')
ax[1, 1].set_title('Model Complexity Comparison')
ax[1, 1].set_xticks(x)
ax[1, 1].set_xticklabels(models, rotation=45, ha='right')
ax[1, 1].tick_params(axis='x', rotation=45)

# Adjust layout to make room for the legend and labels
plt.tight_layout()

# Adjust bottom margin to make room for rotated x-axis labels
plt.subplots_adjust(bottom=0.2)

plt.show()

