# -*- coding: utf-8 -*-
"""Untitled61.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkKBH_DoKsjply4VEXvAZf8QgeVtNZCC
"""

!pip install openpyxl

import pandas as pd
from google.colab import files

# Step 1: Upload files
print("Please upload the traditional methods CSV file.")
traditional_file = files.upload()

print("Please upload the LLM predictions file (Excel or CSV).")
llm_file = files.upload()

try:
    # Get file names
    traditional_file_name = list(traditional_file.keys())[0]
    llm_file_name = list(llm_file.keys())[0]

    # Read traditional methods file (CSV)
    traditional_df = pd.read_csv(traditional_file_name)
    print("Traditional methods file read successfully!")

    # Detect and read LLM file based on extension
    if llm_file_name.endswith('.csv'):
        llm_df = pd.read_csv(llm_file_name)
        print("LLM file is a CSV, read successfully!")
    elif llm_file_name.endswith('.xlsx'):
        llm_df = pd.read_excel(llm_file_name, engine='openpyxl')
        print("LLM file is an Excel file, read successfully!")
    else:
        raise ValueError("Unsupported file format for LLM file. Please upload a CSV or Excel file.")

except Exception as e:
    print(f"Error: {e}")
    raise

import pandas as pd

# File paths (update these if needed)
traditional_file_name = "297countofdatasets-LLM.csv"
llm_file_name = "297-Image Data-LLM (3).xlsx"

# Step 1: Read the traditional methods file (CSV)
traditional_df = pd.read_csv(traditional_file_name)
print("Traditional methods file read successfully!")

# Step 2: Read the LLM file (Excel)
try:
    llm_df = pd.read_excel(llm_file_name, engine='openpyxl')  # Adjusted for Excel files
    print("LLM file read successfully!")
except Exception as e:
    print(f"Error reading LLM file: {e}")

# Step 3: Display the first few rows of both datasets to verify their contents
print("\n--- First few rows of Traditional methods dataset ---")
print(traditional_df.head())  # Display first 5 rows of the traditional dataset

print("\n--- First few rows of LLM dataset ---")
print(llm_df.head())  # Display first 5 rows of the LLM dataset

# Step 4: Show the column names of both datasets
print("\n--- Column names in Traditional methods dataset ---")
print(traditional_df.columns)  # Print column names of the traditional dataset

print("\n--- Column names in LLM dataset ---")
print(llm_df.columns)  # Print column names of the LLM dataset

# Step 5: Display summary statistics (like mean, std, etc.) for both datasets
print("\n--- Summary statistics for Traditional methods dataset ---")
print(traditional_df.describe())  # Summary statistics for the traditional dataset

print("\n--- Summary statistics for LLM dataset ---")
print(llm_df.describe())  # Summary statistics for the LLM dataset